### ISSUE TITLE
[Help] JS Syntax

### ISSUE THREAD

**Issue by ermik** [HaNdTriX/generator-web-extension#10]
@HaNdTriX could you help me change my configs so that I can safely use ES7 / ES-next syntax?

**Comment by HaNdTriX** [comment]
No, but you can either fork https://github.com/handtrix/webextension-toolbox or ask this question on https://stackoverflow.com/.

Nevertheless ES7 should be supported out of the box. 
If not please file an issue on https://github.com/handtrix/webextension-toolbox with more details.
