### ISSUE TITLE
[question] its for many browsers? chrome, safari, opera and firefox?

### ISSUE THREAD

**Issue by joneldiablo** [HaNdTriX/generator-web-extension#14]

**Comment by ermik** [comment]
Yes, with different build / start options you can use the same code to create extension packages using the same code.

There are still many difficulties you may face. This generator and underlying implementation are based on the WebExtension specification that has not been formalized — in fact it is still called a "Draft"

See the current spec https://browserext.github.io/browserext/

**Comment by HaNdTriX** [comment]
thanks @ermik
