### ISSUE TITLE
Please provide details on usingreact with the extension?

### ISSUE THREAD

**Issue by sookinoby** [HaNdTriX/generator-web-extension#3]
What does out of box support for reacct mean?
Should I do npm install react to use react?

**Comment by HaNdTriX** [comment]
You still need to install `react`, `react-dom` and so on, but the preconfigured compiler supports JSX and so on.

**Comment by sookinoby** [comment]
I did something like this 
npm install react react-dom. 
Had a popup page which points to index.js
// app/index.js
import Hello from './hello'
import React from 'react'
import {render} from 'react-dom'
render(<Hello />, document.getElementById('app'))
I get a error Uncaught SyntaxError: Unexpected identifier at the (import statement). Does babel automatically convert the 'import' to statements that the old browsers can understand?

**Comment by sookinoby** [comment]
Upgrading the webextension tool version to 0.1.1 fixes the issues.

If anyone feels babel is not running, just do an npm update, will fix all the issues

**Comment by HaNdTriX** [comment]
Thanks a lot!
