### ISSUE TITLE
browser not defined while running the example

### ISSUE THREAD

**Issue by sookinoby** [HaNdTriX/generator-web-extension#4]
npm run dev -- chrome
Displays browser not defined

**Comment by HaNdTriX** [comment]
Hey @sookinoby 

Thank you for your Feedback. Sound like you installed an old version of `webextension-toolbox`.
Wich version do you have installed?

```bash
$ npm ls webextension-toolbox
```

Please try to run:

```bash
$ npm update webextension-toolbox
```

**Comment by sookinoby** [comment]
When I do npm ls webextension-toolbox, its shows the version as 0.1.1. Can you confirm if this the latest version?
/webextension-toolbox/webextension-toolbox/examples/bookmark-it
└── webextension-toolbox@0.1.1

**Comment by HaNdTriX** [comment]
@sookinoby could you provide some sample code?

**Comment by ermik** [comment]
I'm running mine thru `yarn [scriptname] [parameter]` as in `yarn dev chrome`. Not familiar with NPM as much — but I tried running my setup with a double-dash parameter and got a similar error. Maybe there is an issue there?

**Comment by HaNdTriX** [comment]
Oh I haven‘t tested it with yarn. I‘ll try it tonight. Do you have any example code/Error messages that helps me reproduce your issues?

**Comment by ermik** [comment]
@HaNdTriX my specific case was just with the demo that ships with the generator. Running the `npm` command mentioned above. (I actually have no idea where the README is for how to start this, was it something `yo` says to run next after installation?) If that command is indeed right, here is the crashlog:

```shell
➜ ~/Projects/dev/REDACTED (master) npm run dev --chrome

> REDACTED@0.0.1 start /Users/ermik/Projects/dev/lazard
> webextension-toolbox dev


  error: missing required argument `vendor'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! REDACTED@0.0.1 start: `webextension-toolbox dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the REDACTED@0.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ermik/.npm/_logs/2018-02-08T06_33_12_947Z-debug.log
```
Hope this helps 🙌🏻

**Comment by HaNdTriX** [comment]
@ermik oh you need a space between:

```bash
$ npm run dev -- chrome
````

or try

```bash
$ npm run dev chrome
```

**Comment by HaNdTriX** [comment]
Hey guys

I just wanted to let you know that I am really thankful for your feedback!

@sookinoby Your issue should be fixed in `webextension-toolbox@v0.1.4`.

**Comment by ermik** [comment]
I'm happy with the dash-less option. But:
> @ermik oh you need a space between: `$ npm run dev -- chrome`  

I feel like this is an anti-pattern.

**Comment by HaNdTriX** [comment]
@ermik good point!
I removed this in the documentation.
You can now use

```bash
$ npm run dev chrome
```

```bash
$ npm run dev chrome --version
$ npm run dev chrome --help
...
```

**Comment by sookinoby** [comment]
@HaNdTriX Thank you so much
