### ISSUE TITLE
Packed extensions can't be unzipped 

### ISSUE THREAD

**Issue by ermik** [HaNdTriX/generator-web-extension#6]
After packing an extension and drag&dropping the ZIP into Chrome Extension UI these Errors are displayed:

![alt text](http://i65.tinypic.com/2qapzmh.png "Extension UI Error")

![alt text](http://i68.tinypic.com/b3ue1d.jpg "Extension UI Error")

**Comment by HaNdTriX** [comment]
Thanks!

This issue is related to [webextension-toolbox/issues/10](https://github.com/HaNdTriX/webextension-toolbox/issues/10).

**Comment by ermik** [comment]
So how do I verify that build version is working correctly before sending it to webstore?

**Comment by HaNdTriX** [comment]
Actually the extension should be in your `dist` directory (`dist/chrome`).
The zip task just converts this directory to a zip.

So just "Load unpacked extension..": `dist/chrome`.

If you have a working solution that supports webstore uploads and drag&drop installs feel free to create a PR or reopen this issue.
