### ISSUE TITLE
Question: how does this package handle differences between W3C and Chrome implementations

### ISSUE THREAD

**Issue by ermik** [HaNdTriX/generator-web-extension#7]
I'll keep this brief. Please refer to the respective sections of [Chrome](https://developer.chrome.com/extensions/storage#type-StorageArea) and [Moz](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea) websites on `type StorageArea`.

While W3C Draft (moz) specifies `get` and `set` calls as Iterable (Promises) — Chrome uses a callback to deliver the results.

This would not work in Chrome at the moment:
```javascript
async function amendStorage(key: string, new_data: Object): void {
    let current_data = await browser.storage.sync.get(key);
    browser.storage.sync.set({
        [key]: {
            ...current_data[key],
            new_data
        }
    )
    .then((u) => {
        console.info(`Storage has been updated. Now: ${JSON.stringify(u)}`)
    });
}
```
— because `typeof current_data` is `'undefined'`, as the value returned by `StorageArea.set` (and `get`) in latest consumer Chrome.

I've not tested the extension code from this generator outside Chrome, but I am curious to know what happens in other big browsers supporting the W3C draft (Firefox, Opera, Edge), if the code is written using Chrome's callback-style. _I assume it will crash._

**Comment by ermik** [comment]
I've done some more testing and it's unclear if there is, in fact, a problem. I'll police this for now, but it would be nice to mention how these discrepancies between the W3C Draft and Chromium extension implementation are handled...

**Comment by ermik** [comment]
Recategorized this as a question, as I am trying to nail down what's up with Chrome's callbacks. I'll open it back up and my apologies for the confusion.

Here's another one: `browser.sendMessage` method is [Promise-based](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage) and works in tandem with [Promise-based responses](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessage#addListener_syntax) from 'browser.runtime.onMessage' listener.

[Chrome's implementation](https://developer.chrome.com/extensions/runtime#method-sendMessage) returns nothing from the `chrome.sendMessage` call; there you pass a callback function as an argument to `sendMessage`, which you then call later on. If I use `browser.runtime.sendMessage` in Chrome according to the W3C draft I get this error:  
```
Uncaught (in promise) {message: "Could not establish connection. Receiving end does not exist."}
```

My test case is event-page based, so each part of the extension only fires when the event is dispatched. I've tested this setup with `sendMessage` call in one of the non-persistent background scripts and `onMessage` listener in the `popup.js`. Using Chrome's methods in console everything works fine.

**Comment by sookinoby** [comment]
Do you have your example committed in GitHub? 
Suppose you are sending a message from background script to content script, 
then you have to have a message listener in background script to receive the message 
You have to have a message listener for receiving the response in background script.

**Comment by HaNdTriX** [comment]
Please try to always stick to the [web-extension-spec](https://browserext.github.io/browserext/).
`webextension-toolbox` will detect if you are using the `browser` global in your code and apply a polyfill for chrome and opera accordingly. This is done by a forked version of [mozilla/webextension-polyfill](https://github.com/mozilla/webextension-polyfill)

This means as long as you always use the promise based mozilla api it should work in chrome out of the box.

If you need to know the browsersupport of the specific api use Mozillas excellent Browser compatibility Tables https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea

Here code if you want to understand how webextension-toolbox polyfills the apis: https://github.com/HaNdTriX/webextension-toolbox/tree/master/src/webextension-polyfill

**Comment by ermik** [comment]
Closing this since question should probably be asked in the @browserext core repo.
